apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iot-multiprotocol-example
  annotations:
    github.com/project-slug: sebastianconsuegra95/IoTMultiprotocol
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: other
  lifecycle: Dev
  owner: digital-twins-cell
